### ISSUE TITLE
Can I create boinc2docker WU with custom WU name?

### ISSUE THREAD

**Issue by xFrancisc0** [marius311/boinc2docker#12]
Good afternoon.

I have my project working sucessfully but there is something I'd like to know.

My project will be working for tens of clients. Is there a way to assign WUs custom name using boinc2docker?

For example, for the command:

`bin/boinc2docker_create_work.py image commands`

Could I add the wu custom name somewhere on that command? Something like:

`bin/boinc2docker_create_work.py image commands --wu_name b2d_wu_for_client_usernameX`

Or that's not possible?

**Comment by marius311** [comment]
See `bin/boinc2docker_create_work.py -h`, you just need the `--wu_name` before `image commands`

**Comment by xFrancisc0** [comment]
Thank you!
