### ISSUE TITLE
vboxwrapper has wrong URL in app XML

### ISSUE THREAD

**Issue by hzclarksm** [marius311/boinc2docker#4]
ID    3
Created  17 Oct 2016, 18:18:48 UTC
Application    boinc2docker
Version num    106
Platform    x86_64-pc-linux-gnu
Plan Class  vbox64_mt
XML doc  

<file_info>
    <name>vboxwrapper_26196_x86_64-pc-linux-gnu</name>
    <url>http://www.boincserver.com/boincserver/download/vboxwrapper_26196_x86_64-pc-linux-gnu</url>
    <executable/>

whereas url should be

<url>$master_url/download/vboxwraper_26196_x86_64-pc-linux-gnu</url>

**Comment by marius311** [comment]
Assuming you're using boinc-server-docker, I think I see what's going on. The appversion for boinc2docker is created when you first do a "docker-compose up" on your project (its at that point that the makeproject container gets run, which creates your project folder and updates all the app versions). At that point, the download_url from your project's config.xml file is read and that's what goes in the database as the url for vboxwrapper. 

If you want to change the url's in your config.xml, you need to do so before this happens. That means you need to do so by COPY'ing in your custom config.xml into your custom makeproject image in it's Dockerfile ([here](https://github.com/marius311/cosmohome/blob/master/Dockerfile#L24)'s where it happens for Cosmology@Home).

**Comment by hzclarksm** [comment]
This is what I have in images/makeproject/Dockerfile

FROM boinc/server_makeproject:1.3.4-b2d

COPY project.inc /root/project/html/project/project.inc

COPY config.xml  /root/project/config.xml

**Comment by marius311** [comment]
That looks right, assuming your `config.xml` has the correct URL under `download_url` (just `master_url` is not enough). 

If you're still seeing the problem, it could be you need to reset the database entirely, since once the app is created in there it doesn't get updated. To do this you'll do a `docker-compose down -v`, (the `-v` deletes the volumes, including the one including your project's database). Then just do `docker-compose up` again.

**Comment by hzclarksm** [comment]
Reseting the database seems to have worked.  At this early stage no useful data was lost.

**Comment by marius311** [comment]
Good to hear. Fyi, the correct way to do this kind of thing once your project is actually running is to bump the app_version number every time you need to change something like this. You do this with the `--appver` option to `boinc2docker_create_app`, or alternatively by calling `boinc2docker_create_app` with a YML file with an `appver` key, e.g. like done at CosmologyAtHome. [Heres](https://github.com/marius311/cosmohome/commit/d39ead6ded430207bee8bcdd225c05b800445f9f) an example commit that bumps the app version.
