### ISSUE TITLE
It only creates 2 work units

### ISSUE THREAD

**Issue by JeancarloBarrios** [marius311/boinc2docker#5]
boinc2docker only creates 2 work units for a large problem. Is this normal, i'm new to the whole boinc ordeal . 

Is in python and is just solving a hadamard matrix, i might have chosen the wrong problem for a cluster if so do you have any suggestions.

**Comment by marius311** [comment]
Hi, so the defaults to `boinc2docker_create_work` are the same as those to `create_work`, meaning you get 1 "workunit" and 2 "results". If you want to increase the number of results created, you can use the `--target_nresults` option. If you want to create more workunits, you should just call `boinc2docker_create_work` multiple times.

I'm not familiar with exactly the problem your solving, but the thing to remember with BOINC jobs is that the different parallel tasks can't talk to each other.

**Comment by JeancarloBarrios** [comment]
Thanks it actually help alot
